""" Nowy raz

Revision ID: 8ec4eaaedf0d
Revises: 
Create Date: 2025-08-23 13:11:09.735631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec4eaaedf0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('waga', sa.Float(), nullable=False),
    sa.Column('pas', sa.Integer(), nullable=False),
    sa.Column('posladek', sa.Integer(), nullable=False),
    sa.Column('klatka', sa.Integer(), nullable=False),
    sa.Column('udo_l', sa.Integer(), nullable=False),
    sa.Column('udo_p', sa.Integer(), nullable=False),
    sa.Column('lydka_l', sa.Integer(), nullable=False),
    sa.Column('lydka_p', sa.Integer(), nullable=False),
    sa.Column('biceps_l', sa.Integer(), nullable=False),
    sa.Column('biceps_p', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('folder_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_entry_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_entry_id'], ['measurement_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement_images')
    op.drop_table('measurement_entries')
    # ### end Alembic commands ###
